services:
    # traefik

    backend:
        ports:
            - "3000:3000"

    # postgres-ssl-bootstrap

    postgres:
        ports:
            - "5432:5432"

    redis:
        ports:
            - "6379:6379"

    typesense:
        ports:
            - "8108:8108"

    gorse:
        ports:
            - "8088:8088"

    minio:
        ports:
            - "9000:9000"
            - "9001:9001"

    auth:
        ports:
            - "9100:9100"
            - "9999:9999"
